apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-xw1x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-xw1x
    app.kubernetes.io/part-of: test-app-889
  name: nodejs-no-dockerfile-xw1x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-xw1x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-xw1x
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-889/nodejs-no-dockerfile-xw1x@sha256:3fed062f4bc924871e05a98d0874cf7de149f1fc73e112d14c6cc1643dd7b3b0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
