apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-xw1x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-xw1x
    app.kubernetes.io/part-of: test-app-889
  name: nodejs-no-dockerfile-xw1x
spec:
  ports:
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: nodejs-app
    app.kubernetes.io/instance: nodejs-no-dockerfile-xw1x
status:
  loadBalancer: {}
