apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-hae3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-both-tag-digest-hae3
    app.kubernetes.io/part-of: test-app-889
  name: e2e-tests-parent-image-with-both-tag-digest-hae3
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-hae3
status:
  loadBalancer: {}
