apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-qfdt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-qfdt
    app.kubernetes.io/part-of: test-app-889
  name: pip-e2e-test-qfdt
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-qfdt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-qfdt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-889/pip-e2e-test-qfdt@sha256:930e87e3b8d7cfeb2c78030c5d605a05cc3780f5274393170eb0e5725b4763a8
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
