apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-xw8c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-xw8c
    app.kubernetes.io/part-of: test-app-889
  name: retrodep-xw8c
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-xw8c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-xw8c
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-889/retrodep-xw8c@sha256:05d6276d7e5e24f08275555f741b954c79a41ed47326c93f45269bf7eac9f2f4
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
