apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-1sxf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-1sxf
    app.kubernetes.io/part-of: test-app-889
  name: e2e-tests-parent-image-with-digest-only-1sxf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-1sxf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-1sxf
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-889/e2e-tests-parent-image-with-digest-only-1sxf@sha256:6a5ea09c92cf478584077a781216556919e1eda2ed6e11818a7f4ef8a44d7639
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
